// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABEVVYFVhCzeydXiEeN30ZUjD2zFNqu9c',
    appId: '1:975139522831:web:6bca647fdb6ce27fffd67a',
    messagingSenderId: '975139522831',
    projectId: 'whoami-f337f',
    authDomain: 'whoami-f337f.firebaseapp.com',
    databaseURL: 'https://whoami-f337f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whoami-f337f.appspot.com',
    measurementId: 'G-4HM2WVXEJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfMqR8NMgCRHzQW8UlgM-70baDC4erVUQ',
    appId: '1:975139522831:android:15433eb1306945d5ffd67a',
    messagingSenderId: '975139522831',
    projectId: 'whoami-f337f',
    databaseURL: 'https://whoami-f337f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whoami-f337f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYZFojcYZJ3q5OtT0R87mHy0LkMfiZ-k',
    appId: '1:975139522831:ios:bdfe6715b47a4d9cffd67a',
    messagingSenderId: '975139522831',
    projectId: 'whoami-f337f',
    databaseURL: 'https://whoami-f337f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whoami-f337f.appspot.com',
    iosBundleId: 'com.example.whoAmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYZFojcYZJ3q5OtT0R87mHy0LkMfiZ-k',
    appId: '1:975139522831:ios:73dbc73337e23a7bffd67a',
    messagingSenderId: '975139522831',
    projectId: 'whoami-f337f',
    databaseURL: 'https://whoami-f337f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whoami-f337f.appspot.com',
    iosBundleId: 'com.example.whoAmi.RunnerTests',
  );
}
