name: who_am_i
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  bloc: ^8.1.4
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_database: ^10.4.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  
  freezed_annotation: ^2.4.1
  share_plus: ^8.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7

flutter:
  uses-material-design: true
